      SUBROUTINE GDCRDP(D,ND,X,NX)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    GDCRDP      GET GRID COORDS FOR MONOTONIC INCREASING
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 90-10-11
C
C ABSTRACT: GET GRID COORDS FOR MONOTONIC INCREASING POINTS.
C
C PROGRAM HISTORY LOG:
C   90-10-11  PARRISH
C
C   INPUT ARGUMENT LIST:
C     D,ND     - INPUT POINTS, NUMBER OF INPUT POINTS.
C     X,NX     - VALUES, NUMBER OF REFERENCE GRID POINTS.
C
C   OUTPUT ARGUMENT LIST:
C     D        - CONVERTED TO GRID UNITS.
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
      DIMENSION D(ND),X(NX)
C--------
      DO 400 ID=1,ND
        DT=D(ID)
        IF(DT .LE. X(1))THEN
          D(ID)=1.+(DT-X(1))/(X(2)-X(1))
        ELSE
          IX=ISRCHFGE(NX-1,X,1,DT)-1
          D(ID)=FLOAT(IX)+(DT-X(IX))/(X(IX+1)-X(IX))
        END IF
400   CONTINUE
      RETURN
      END
