      SUBROUTINE PREPPW(DRPTPW,DLONS,DLATS,DPW,RMAXERR,
     *  TTYPES,NPWDAT,NSIG,NLAT,NLON,GLATS,
     *  GLONS)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PREPPW     PRELIMINARY STUFF BEFORE RES. CALC. PW
C   PRGMMR: DERBER          ORG: W/NMC23    DATE: 91-02-25
C
C ABSTRACT: PRELIMINARY STUFF BEFORE RESIDUAL CALCULATION FOR PREC. WATER
C
C PROGRAM HISTORY LOG:
C   91-03-25  DERBER
C
C   INPUT ARGUMENT LIST:
C     DRPTPW   - OBS TYPE IN, OBS ERROR OUT (MM UNITS)
C     DLONS,DLATS - OBS LONGITUDES AND LATITUDES (RADIANS IN AND OUT)
C     DPW      - P.W. (MM; FULL VALUE IN,  RESIDUAL OUT)
C     NPWDAT   - NUMBER OF OBSERVATIONS
C     NSIG     - NUMBER OF SIGMA LEVELS
C     NLAT     - NUMBER OF GAUSSIAN LATS POLE TO POLE
C     NLON     - NUMBER OF LONGITUDES
C     GLATS,GLONS - GRID LATITUDES AND LONGITUDES
C
C   OUTPUT ARGUMENT LIST:
C     RMAXERR  - MAXIMUM ALLOWED ERROR
C     TTYPES   - PREPDA OBSERVATION TYPES
C     AND AS INDICATED ABOVE
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C--------
      DIMENSION DRPTPW(NPWDAT),DLONS(NPWDAT)
      DIMENSION DLATS(NPWDAT),DPW(NPWDAT)
      DIMENSION GLATS(NLAT),GLONS(NLON)
      DIMENSION TTYPES(NPWDAT)
      DIMENSION RMAXERR(NPWDAT)
C-------
C-------- CONVERT OBS LATS AND LONS TO GRID COORDINATES
C--------
      CALL GDCRDP(DLATS,NPWDAT,GLATS,NLAT)
      CALL GDCRDP(DLONS,NPWDAT,GLONS,NLON)
      DO 1 I=1,NPWDAT
      DRPTPW(I)=1./DRPTPW(I)**2
   1  CONTINUE
      RETURN
      END
