      SUBROUTINE RDFACT(FACTOR,IDATEG,HOURG,NLATH,NLON,ISFC)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RDFACT  READ AND COMPUTE FACTOR       
C   PRGMMR: DERBER           ORG: W/NMC23    DATE: 92-09-08
C
C ABSTRACT: READ IN FACTOR FOR USE IN REDUCING TO 10M WINDS          
C
C PROGRAM HISTORY LOG:
C   92-09-08  DERBER 
C
C   INPUT ARGUMENT LIST:
C     ISFC     - UNIT NUMBER OF BGES FILE
C     IDATEG   - DATE TIME ARRAY FOR GUESS
C     HOURG    - HOUR OF GUESS
C     NLATH    - NUMBER OF LATITUDES ON GAUSSIAN GRID
C     NLON     - NUMBER OF LONGITUDES ON GAUSSIAN GRID
C
C   OUTPUT ARGUMENT LIST:
C     FACTOR   - FACTOR FOR REDUCING BOTTOM SIGMA VALUES TO 10M
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C
C-CRA          DIMENSION FLDR (NLON,2*NLATH-2)
C-CRA          REAL FACTOR(2*NLATH+1,NLON+2)
C-CRA          INTEGER IDATEG(4)
C-CRA          INTEGER LAB85(8),IDATE(4)          
C-CRA          INTEGER IDATE5(5)
 
          DIMENSION FLDR (192,2*48-2)
          REAL FACTOR(2*48+1,192+2)
          INTEGER IDATEG(4)
          INTEGER LAB85(8),IDATE(4)          
          INTEGER IDATE5(5)
C--------
C-------- SCRATCH SPACE
C--------
C
C
C   READ SURFACE FILE TO GET 10M WINDS
C
C-CRA                FACTOR=1.   
C       REAL FACTOR(2*NLATH+1,NLON+2)
          DO ITMP=1,(2*NLATH+1)*(NLON+2)
          FACTOR(ITMP,1)=1.   
          ENDDO
      PRINT *, 'CALCULATING FACTOR'
      REWIND ISFC
      READ (ISFC,END=7781,ERR=7781) LAB85
      READ (ISFC,END=7781,ERR=7781) FHOUR,IDATE
      IDATE5(1)=IDATEG(4)
      IDATE5(2)=IDATEG(2)
      IDATE5(3)=IDATEG(3)
      IDATE5(4)=IDATEG(1)
      IDATE5(5)=0
      CALL W3FS21(IDATE5,NMING)
      NMING=NMING+60*HOURG
      IDATE5(1)=IDATE(4)
      IDATE5(2)=IDATE(2)
      IDATE5(3)=IDATE(3)
      IDATE5(4)=IDATE(1)
      IDATE5(5)=0
      CALL W3FS21(IDATE5,NMINS)
      NMINS=NMINS+60*FHOUR
      PRINT 101,FHOUR,IDATE
  101 FORMAT(' FHOUR=',F5.0,' IDATE=',4I5)
      PRINT *,' FOR BGES FILE, NMINS=',NMINS
      PRINT *,' FOR GES FILE, NMING=',NMING
      IF(NMINS.NE.NMING) GO TO 7781
C
      DO 102 J = 1,13
C
        READ(ISFC,END=7781,ERR=7781)
  102 CONTINUE
      READ(ISFC,END=7781,ERR=7781) FLDR
      DO 1101 J=1,NLON
      DO 1101 I = 1, 2*NLATH-2
        FACTOR(I+1,J)=FLDR(J,2*NLATH-1-I)
 1101 CONTINUE
C
      SUMN=0.
      SUMS=0.
      DO 780 J=1,NLON
        SUMN=FACTOR(2*NLATH-1,J) +SUMN
        SUMS=FACTOR(2,J) +SUMS
 780  CONTINUE
      SUMN=SUMN/NLON
      SUMS=SUMS/NLON
      DO 781 J=1,NLON
        FACTOR(2*NLATH,J)=SUMN
        FACTOR(1,J)=SUMS
 781  CONTINUE
      XMAX=-1.E20
      XMIN=1.E20
      DO 1102 J=1,NLON
      DO 1102 I = 1, 2*NLATH-2
        XMAX=MAX(FACTOR(I,J),XMAX)
        XMIN=MIN(FACTOR(I,J),XMIN)
 1102 CONTINUE
      PRINT *, 'FACTOR  MAX AND MIN = ',XMAX,XMIN
7781  CONTINUE
      CLOSE(ISFC)
      RETURN    
      END
