      SUBROUTINE RESIDW(DPRES,DU,DV,
     *  RTYPES,RSPRES,MWDAT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RESIDW      COMPUTE WIND RESIDUALS.
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 90-10-11
C
C ABSTRACT: FORM WIND RESIDUALS, GET OBS ERROR, AND PRINT STATS.
C
C PROGRAM HISTORY LOG:
C   90-10-11  PARRISH
C
C   INPUT ARGUMENT LIST:
C     DPRES    - PRES (MB*10+QM IN, GRID COORDS IN SIGMA OUT)
C     DU,DV    - U,V WND IN, RESIDUALS OUT
C     RTYPES   - PREPDA OBSERVATION TYPES
C     RSPRES   - OBSERVATION PRESSURES
C     MWDAT    - NUMBER OF OBSERVATIONS
C
C   OUTPUT ARGUMENT LIST:
C     AS INDICATED ABOVE
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C--------
      DIMENSION DPRES(MWDAT)
      DIMENSION DU(MWDAT),DV(MWDAT)
      DIMENSION RTYPES(MWDAT)
      DIMENSION RSPRES(MWDAT)
C--------
C--------  LIMIT TO BE ABOVE BOTTOM OF MODEL
C--------
      DO 49 I=1,MWDAT
        IF(DPRES(I) .LT. 1.) DPRES(I)=1.
49    CONTINUE
C--------
C-------- NOW DO STATISTICS SUMMARY
C--------
      SCALE=1.
      PTOP=800.
      PBOT=900.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF 850MB WIND DATA, RANGES IN M/S$')
      PTOP=450.
      PBOT=550.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF 500MB WIND DATA, RANGES IN M/S$')
      PTOP=225.
      PBOT=275.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF 250MB WIND DATA, RANGES IN M/S$')
      PTOP=75.
      PBOT=125.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF 100MB WIND DATA, RANGES IN M/S$')
      PTOP=0.
      PBOT=74.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF 50MB WIND DATA, RANGES IN M/S$')
      PTOP=0.
      PBOT=2000.
      CALL DVAST(RTYPES,DU,DV,SCALE,MWDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT VFIT OF ALL WIND DATA, RANGES IN M/S$')
      RETURN
      END
