      SUBROUTINE RESPSF(DPS,TTYPES,MPSDAT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RESPSF      PRINT SURFACE STATS.
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 90-10-10
C
C ABSTRACT: PRINT SURFACE STATS.
C
C PROGRAM HISTORY LOG:
C   90-10-10  PARRISH
C
C   INPUT ARGUMENT LIST:
C     DPS      - PRES (MB*10+QM IN, LN(PS) RESIDUAL OUT--P IN CB)
C     TTYPES   - PREPDA OBSERVATION TYPES
C     MPSDAT   - NUMBER OF OBSERVATIONS
C
C   OUTPUT ARGUMENT LIST:
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C--------
C
C-CRA          DIMENSION DPS(MPSDAT)
C-CRA          DIMENSION TTYPES(MPSDAT)
C-CRA          DIMENSION PP(MPSDAT)
 
C          DIMENSION DPS(_MPSDAT_)
C          DIMENSION TTYPES(_MPSDAT_)
C          DIMENSION PP(_MPSDAT_)
          DIMENSION DPS(18000)
          DIMENSION TTYPES(18000)
          DIMENSION PP(18000)
C--------
C-------- NOW DO STATISTICS SUMMARY
C--------
      SCALE=1000.
C-CRA                PP=1000.
C       DIMENSION PP(MPSDAT)
          DO ITMP=1,MPSDAT
          PP(ITMP)=1000.
          ENDDO
      PTOP=0.
      PBOT=2000.
      CALL DTAST(TTYPES,DPS,SCALE,MPSDAT,PP,PBOT,PTOP,
     *  'CURRENT FIT OF SURFACE PRESSURE DATA, RANGES IN MB$')
      RETURN
      END
