      SUBROUTINE RESSAT(DPRES,DT,RTYPES,RSPRES,MTDAT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RESSAT      PRINT STATS FOR SAT. TEMPERATURES
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 90-10-11
C
C ABSTRACT: PRINT STATS FOR SAT. TEMPERATURES.
C
C PROGRAM HISTORY LOG:
C   90-10-11  PARRISH
C
C   INPUT ARGUMENT LIST:
C     DPRES    - PRES (MB*10+QM IN, GRID COORDS IN SIGMA OUT)
C     DT       - TEMPS IN, RESIDUAL OUT
C     RTYPES   - PREPDA OBSERVATION TYPES
C     PSPRES   - OBSERVATION PRESSURES
C     MTDAT    - NUMBER OF OBSERVATIONS
C
C   OUTPUT ARGUMENT LIST:
C     NONE              
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C--------
      DIMENSION DPRES(MTDAT),DT(MTDAT)
      DIMENSION RTYPES(MTDAT)
      DIMENSION RSPRES(MTDAT)
C--------
C--------
C-------- NOW DO STATISTICS SUMMARY
C--------
      SCALE=1.
      PTOP=800.
      PBOT=900.
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF 850MB SAT. TEMPERATURE DATA, RANGES IN K$')
      PTOP=450.
      PBOT=550.
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF 500MB SAT. TEMPERATURE DATA, RANGES IN K$')
      PTOP=225.
      PBOT=275.
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF 250MB SAT. TEMPERATURE DATA, RANGES IN K$')
      PTOP=75.
      PBOT=125.
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF 100MB SAT. TEMPERATURE DATA, RANGES IN K$')
      PTOP=0.
      PBOT=74.9
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF  50MB SAT. TEMPERATURE DATA, RANGES IN K$')
      PTOP=0.
      PBOT=2000.
      CALL DTAST(RTYPES,DT,SCALE,MTDAT,RSPRES,PBOT,PTOP,
     *  'CURRENT FIT OF ALL SAT. TEMPERATURE DATA, RANGES IN K$')
      RETURN
      END
