      PROGRAM SSI
C$$$  MAIN PROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C MAIN PROGRAM:  SSI    SPECTRAL STATISTICAL INTERPOLATION
C   PRGMMR: PARRISH          ORG: W/NMC22     DATE: 92-09-16
C
C ABSTRACT: THE SPECTRAL STATISTICAL INTERPOLATION ANALYSIS ROUTINE
C   PERFORMS A GLOBAL ANALYSIS FOR THE GLOBAL SPECTRAL MODEL.  THIS
C   ANALYSIS IS PERFORMED DIRECTLY IN SPECTRAL COEFFICIENTS AND IN
C   SIGMA COORDINATES.  FURTHER DETAILS OF THE ANALYSIS SYSTEM CAN
C   BE FOUND IN PARRISH AND DERBER (1992) THE NATIONAL
C   METEOROLOGICAL CENTERS SPECTRAL STATISTICAL INTERPOLATION
C   ANALYSIS SYSTEM. MON. WEA. REV.
C
C PROGRAM HISTORY LOG:
C   91-XX-XX  PARRISH/DERBER
C   91-12-10  PARRISH/DERBER   FIXED CODING ERROR IN NEAR SFC ANAL
C   92-09-14  DERBER           IMPROVED VERSION OF GLOBAL ANALYSIS
C
C **** NOTE: THE FOLLOWING RULES ARE MANDATORY FOR CRAY PROGRAMS ****
C *                                                                 *
C *          (1) USE UNIT NUMBERS 11-49 FOR ALL INPUT FILES.        *
C *          (2) USE UNIT NUMBERS 51-89 FOR ALL OUTPUT FILES.       *
C *          (3) USE UNIT NUMBERS 90-99 FOR WORK FILES THAT ARE     *
C *              INTERNAL TO THE PROGRAM AND USED ONLY IN THE       *
C *              PROGRAM UNIT.                                      *
C *          (4) UNIT NUMBERS 1-4, 8-10 AND 50 ARE RESERVED FOR     *
C *              FUTURE USE.                                        *
C *                                                                 *
C ****  EXCEPT FOR WORK FILES, A UNIT NUMBER SHOULD NOT BE USED     *
C *     FOR BOTH INPUT AND OUTPUT.                                  *
C *******************************************************************
C
C USAGE:
C   INPUT FILES:
C **************************
C    UNIT NUMBERS ARE SPECIFIED FOR MOST FILES ON
C    INPUT DATA CARDS. CAN BE CHANGED BY CHANGING DATA CARDS
C **************************
C     INPREP   - INPUT BUFR DATA FILE FROM QUALITY CONTROL ROUTINE
C     INGES    - SIX HOUR FORECAST GUESS FIELD
C     IDIVT    - DIVERGENCE TENDENCY ERROR VARIANCE ESTIMATES
C     INEOFS   - INPUT STATISTICS FILE
C     ISFC     - BGES FILE
C     ISAT     - SATELLITE ERROR COVARIANCE FILE
C     IIANL    - PREVIOUS ANALYSIS FILE          
C
C   OUTPUT FILES:  (INCLUDING SCRATCH FILES)
C     IOANL    - OUTPUT ANALYSIS FILE IN SIGMA COORDINATES
C     JSAT     - WORK FILE SATELLITE DATA
C     ISCRA    - WORK FILE CONVENTIONAL DATA
C     ISCRA3   - WORK FILE--SAVE REF FIELDS FOR DIV-TEND TAN LIN MODEL
C     FORT.6   - PRINTOUT
C
C   SUBPROGRAMS CALLED:
C     UNIQUE:    - SUBROUTINES:
C                - CHLML,CONVERC,DTAST,DVAST,G2S0,G2S1,GDCRDN,
C                - GDCRDP,GENQSAT,GETLALO,GETLALOH,GLBSOI,GTBHALF,
C                - HOPER,HTOPER,INGUESS,INITPS,INITQPW,INITSAT,INITT,INITW,
C                - INTPS,INTQPW,INTRP2,INTRP3,INTT,INTW,M1FAX,M1FFTA,M1FFTB,
C                - M1FTRG,M1GLAT,M1IPQR,M1POLY,M1RCONS,M1VPAS,M2FFTM,PCGSOI,
C                - PREPP,PREPPW,PREPQ,PREPS,PREPT,PREPW,PRNON85,RDFACT,RDGESC,
C                - RDPREP,RDTEST,RESIDW,RESPSF,RESPW,RESQ,RESSAT,RESTMP,S2G0,
C                - S2G1,S2MG2X,SATC,SATCOV,SATOP4,SETUPRHS,SPRP,SPRQPW,SPRS,
C                - SPRT,SPRUV,TG2S0.F,TRANPW,W3FA03,WRANLC             
C
C                - FUNCTION CONMC
C     LIBRARY:
C       W3LIB    -
C
C   EXIT STATES:
C     COND =   0 - SUCCESSFUL RUN
C          =  55 - INCOMPATABLE EOF FILE
C          =  56 - TROUBLE IN CONMC
C
C REMARKS: RESOLUTION, UNIT NUMBERS AND SEVERAL CONSTANTS ARE
C          IN THE INPUT DATA CARDS
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 8X (EXTENSIVE USE OF DYNAMIC MEMORY FEATURE)
C   MACHINE:  CRAY
C

      DIMENSION A(4)
      CHARACTER*4 ON85DT(8)
C
C--------
      NAMELIST/NAMANAL/A,INPREP,INGES,IIANL,JCAP,
     *   NSIG,NLATH,NLON,ISFC,
     *   NITER,IOANL,INEOFS,
     *   ISAT,JSAT,ISCRA,MITER,ISCRA3,AMPDIVT,DAMPDIVT,
     *   ERMAXT,ERMAXW,ERMAXP,ERMAXQ,ERMAXPW,
     *   ERMINT,ERMINW,ERMINP,ERMINQ,ERMINPW,
     *   GROSST,GROSSST,GROSSW,GROSSP,GROSSQ,GROSSPW
      DATA A/4*0.2737/,INPREP/30/
      DATA INGES/35/,IIANL/36/,JCAP/126/,NSIG/28/
      DATA ISFC/37/
      DATA NLATH/96/,NLON/384/,NPRCP/72960/,NITER/100/
      DATA IOANL/51/,INEOFS/49/,NBLK/40/
      DATA ISAT/48/,JSAT/94/,ISCRA/97/,MITER/2/
      DATA ISCRA3/98/,AMPDIVT/1./,DAMPDIVT/1./,IDIVT/47/
      DATA ERMAXT/5.6/,ERMAXW/6.1/,ERMAXP/3./,ERMAXQ/100./
      DATA ERMINT/1.3/,ERMINW/1.4/,ERMINP/1./,ERMINQ/10./
      DATA ERMAXPW/8./,ERMINPW/2./
      DATA GROSST/20./,GROSSST/20./,GROSSW/20./
      DATA GROSSP/20./,GROSSQ/20./,GROSSPW/20./
C--------
C-MK  CALL W3LOG('$92290.75','ANALYF  ')
C-MK  CALL W3TAGB('ANALYF  ',0092,0290,0075,'NMC23 ')
C--------
C--------
C--------  READ REMAINING INPUT PARAMETERS
C--------
      READ(5,NAMANAL)
      WRITE(6,200)
C     WRITE(0,200)
200   FORMAT(' CALLING GLBSOI WITH FOLLOWING INPUT PARAMETERS:',/)
      WRITE(6,NAMANAL)
C     WRITE(0,NAMANAL)

C--------

C--------
      CALL RDTEST(INPREP,ON85DT,NTDATA,NSDATA,NWDATA,
     *            NPDATA,NQDATA,NPWDAT,NQTDATA,NSPROF)
      CALL GLBSOI(INPREP,INGES,IIANL,JCAP,NSIG,
     *   NLATH,NLON,INEOFS,NITER,MITER,IOANL,A,ISAT,JSAT,
     *   ISFC,ISCRA,NBLK,ISCRA3,AMPDIVT,DAMPDIVT,IDIVT,
     *   ON85DT,NTDATA,NSDATA,NWDATA,NPDATA,NQDATA,NPWDAT,NQTDATA,
     *   NSPROF,
     *   ERMAXT,ERMAXW,ERMAXP,ERMAXQ,ERMAXPW,
     *   ERMINT,ERMINW,ERMINP,ERMINQ,ERMINPW,
     *   GROSST,GROSSST,GROSSW,GROSSP,GROSSQ,GROSSPW)
C-MK  CALL W3LOG('$E')
C-MK  CALL W3TAGE('ANALYF  ')
      STOP
      END
