      SUBROUTINE WRANLC(ZC,DC,TC,QC,PC,RC,HOURG,IDATEG,SIGI,SIGL,
     *  IOANL,JCAP,NSIG,ON85,ON85DT,LM2ML,FACTSML,FACTVML)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    WRANLC     REORDER AND WRITE SIGMA COEFS.
C   PRGMMR: PARRISH          ORG: W/NMC22    DATE: 90-10-10
C
C ABSTRACT: REORDER FROM INTERNAL FORMAT AND WRITE SIGMA COEFS.
C
C PROGRAM HISTORY LOG:
C   90-10-10  PARRISH
C
C   INPUT ARGUMENT LIST:
C     ZC,DC,TC,QC,PR,RC - ANALYSIS SIGMA COEFS FOR VORT,DIV, ETC
C     HOURG    - ANALYSIS FORECAST HOUR
C     IDATEG   - INITIAL DATE OF ANALYSIS
C     SIGI     - SIGMA VALUES AT INTERFACE OF EACH SIGMA LAYER
C     SIGL     - SIGMA VALUES AT MID-POINT OF EACH SIGMA LAYER
C     IOANL    - UNIT NUMBER OF ANALYSIS COEFS
C     JCAP     - TRIANGULAR TRUNCATION
C     NSIG     - NUMBER OF SIGMA LEVELS
C     ON85     - ON85 DATE RECORD FOR GUESS COEFS
C     ON85DT   - ON85 DATE RECORD FOR DATA
C
C   OUTPUT ARGUMENT LIST:
C     NO OUTPUT ARGUMENTS
C
C ATTRIBUTES:
C   LANGUAGE: CFT77
C   MACHINE:  CRAY YMP
C
C$$$
C
C-CRA          DIMENSION ZC((JCAP+1)*(JCAP+2),NSIG)
C-CRA          DIMENSION DC((JCAP+1)*(JCAP+2),NSIG)
C-CRA          DIMENSION TC((JCAP+1)*(JCAP+2),NSIG)
C-CRA          DIMENSION QC((JCAP+1)*(JCAP+2),NSIG)
C-CRA          DIMENSION PC((JCAP+1)*(JCAP+2))
C-CRA          DIMENSION RC((JCAP+1)*(JCAP+2))
C-CRA          DIMENSION IDATEG(4),SIGI(NSIG+1),SIGL(NSIG)
C-CRA          DIMENSION LM2ML((JCAP+1)*(JCAP+2))
C-CRA          DIMENSION FACTSML((JCAP+1)*(JCAP+2))
C-CRA          DIMENSION FACTVML((JCAP+1)*(JCAP+2))
C-CRA          DIMENSION DUMMY(201-NSIG-1-NSIG)
C-CRA          DIMENSION Z((JCAP+1)*(JCAP+2))
 
          DIMENSION ZC((62+1)*(62+2),28)
          DIMENSION DC((62+1)*(62+2),28)
          DIMENSION TC((62+1)*(62+2),28)
          DIMENSION QC((62+1)*(62+2),28)
          DIMENSION PC((62+1)*(62+2))
          DIMENSION RC((62+1)*(62+2))
          DIMENSION IDATEG(4),SIGI(28+1),SIGL(28)
          DIMENSION LM2ML((62+1)*(62+2))
          DIMENSION FACTSML((62+1)*(62+2))
          DIMENSION FACTVML((62+1)*(62+2))
          DIMENSION DUMMY(201-28-1-28)
          DIMENSION Z((62+1)*(62+2))

C          INTEGER IWASH(2)
           CHARACTER*4 ON85(8),ON85DT(8)
C          CHARACTER*4 CWASH(4)
C--------
C-------- LOCAL SPACE
C--------
C     EQUIVALENCE (CWASH,IWASH)
C     DATA IWASH/X'00000000E6C1E2C8',X'C9D5C7E3D6D5C3E1'/

      INTEGER IWASH(4,4)
      DATA IWASH/0,0,0,0, 230,193,226,200,
     1   201,213,199,227, 214,213,195,225/

C--------
C-------- SET UP INDEX ARRAYS FOR CONVERTING TO OUTPUT COEFS
C--------
      NC=(JCAP+1)*(JCAP+2)
C--------
C-------- FIX UP STUFF FOR RECORD # 2
C--------
C-CRA                DUMMY=0.
C       DIMENSION DUMMY(201-NSIG-1-NSIG)
          DO ITMP=1,201-NSIG-1-NSIG
          DUMMY(ITMP)=0.
          ENDDO
      WAVES=JCAP
      XLAYERS=NSIG
      TRUN=1.
      ORDER=2.
      REALFORM=1.
C-----------------------FOLLOWING 2 LINES CORRECTED ON
C---------------------MARK IRDELL REQUEST, 2-9/94  (DP)
      GENCODE=78.
      IF(JCAP.EQ.62) GENCODE=80.
C--------
C-------- UPDATE ON85 DATE WORD AND IDATE, USING DATE WORD FROM
C-------- DATA.
C--------
C     DO I=1,4
C      ON85(4+I)=CWASH(I)
C     END DO
      DO I = 1, 4
          DO J = 1, 4
             ON85(4+I)(J:J) = CHAR(IWASH(J,I))
          ENDDO   
      ENDDO       

      PRINT *,' ON85 FOLLOWS:'
      CALL PRNON85(ON85)
      PRINT *,' ON85DT FOLLOWS:'
      CALL PRNON85(ON85DT)
	WRITE(*,*) '>>W3FS03: IHOUR,IYEAR,MONTH,IDAY=',
     1      IHOUR,IYEAR,MONTH,IDAY

      CALL W3FS03(ON85DT(3),IHOUR,IYEAR,MONTH,IDAY,1)

	WRITE(*,*) '<<W3FS03: IHOUR,IYEAR,MONTH,IDAY=',
     1      IHOUR,IYEAR,MONTH,IDAY
	WRITE(*,*) 'IDATEG(4)=',IDATEG(4)

      IDATEG(1)=IHOUR
      IDATEG(2)=MONTH
      IDATEG(3)=IDAY
C
C     IYEAR IS 2 DIGIT .. WANT 4 DIGIT CODE
C        EITHER SAME GUESS AS INITIAL GUESS OR NEXT YEAR
      IF (MOD(IDATEG(4),100).NE.IYEAR) THEN
	  IDATEG(4) = IDATEG(4) + 1
      ENDIF

      ON85(3)=ON85DT(3)
C--------
      REWIND IOANL
C-------- HOUR,IDATE, ETC.
      WRITE(IOANL)ON85
      PRINT *,' ON85 WRITTEN TO OUTPUT COEFS FILE FOLLOWS:'
      CALL PRNON85(ON85)
      WRITE(IOANL)HOURG,IDATEG,SIGI,SIGL,DUMMY,WAVES,XLAYERS,TRUN,
     *   ORDER,REALFORM,GENCODE
C-------- TERRAIN COEFS
      DO I=1,NC
       Z(I)=FACTSML(I)*RC(LM2ML(I))
      END DO
      WRITE(IOANL)Z
C-------- SFCP COEFFICIENTS
      DO I=1,NC
       Z(I)=FACTSML(I)*PC(LM2ML(I))
      END DO
      WRITE(IOANL)Z
C-------- TEMP COEFFICIENTS
      DO K=1,NSIG
       DO I=1,NC
        Z(I)=FACTSML(I)*TC(LM2ML(I),K)
       END DO
       WRITE(IOANL)Z
      END DO
C------- DIV AND VORT
      DO K=1,NSIG
       DO I=1,NC
        Z(I)=FACTVML(I)*DC(LM2ML(I),K)
       END DO
       WRITE(IOANL)Z
       DO I=1,NC
        Z(I)=FACTVML(I)*ZC(LM2ML(I),K)
       END DO
       WRITE(IOANL)Z
      END DO
C-------- Q COEFS
      DO K=1,NSIG
       DO I=1,NC
        Z(I)=FACTSML(I)*QC(LM2ML(I),K)
       END DO
       WRITE(IOANL)Z
      END DO
      WRITE(6,700)JCAP,NSIG,HOURG,IDATEG
700   FORMAT(' SOME SIGMA COEFFICIENTS WRITTEN, JCAP,NSIG=',
     *   2I6,/,' HOUR,IDATE=',F10.1,4I5)
       REWIND IOANL
       CLOSE (IOANL)
      RETURN
      END
