all:
	cd gribw_lib.cd ; make
	cd cdas2_v1_acqc.fd ; make
	cd cdas2_v1_combbufr.fd ; make
	cd cdas2_v1_cqc.fd ; make
	cd cdas2_v1_fcst.fd ; make
	cd cdas2_v1_gribpentad.cd ; make
	cd cdas2_v1_oiqc.fd ; make
	cd cdas2_v1_pgb.fd ; make
	cd cdas2_v1_postvents.fd ; make
	cd cdas2_v1_precipadj.fd ; make
	cd cdas2_v1_prepdate.fd ; make
	cd cdas2_v1_prevents.fd ; make
	cd cdas2_v1_sfc.fd ; make
	cd cdas2_v1_sgb.fd ; make
	cd cdas2_v1_sig2sig.fd ; make
	cd cdas2_v1_sigdate.fd ; make
	cd cdas2_v1_ssi.fd ; make
	cd cdas2_v1_fix_snowc.cd ; make
	cd cdas2_v1_snowd2snowc.cd ; make
	cd cdas2_v1_fix_afwa_snow.cd  ; make
	cd cdas2_v1_fix_snowc.cd ; make
	cp *.fd/cdas2_v1* *.cd/cdas2_v1* ../exec

clean:
	cd gribw_lib.cd; make clean
	cd cdas2_v1_acqc.fd ; make clean
	cd cdas2_v1_combbufr.fd ; make clean
	cd cdas2_v1_cqc.fd ; make clean
	cd cdas2_v1_fcst.fd ; make clean
	cd cdas2_v1_gribpentad.cd ; make clean
	cd cdas2_v1_oiqc.fd ; make clean
	cd cdas2_v1_pgb.fd ; make clean
	cd cdas2_v1_postvents.fd ; make clean
	cd cdas2_v1_precipadj.fd ; make clean
	cd cdas2_v1_prepdate.fd ; make clean
	cd cdas2_v1_prevents.fd ; make clean
	cd cdas2_v1_sfc.fd ; make clean
	cd cdas2_v1_sgb.fd ; make clean
	cd cdas2_v1_sig2sig.fd ; make clean
	cd cdas2_v1_sigdate.fd ; make clean
	cd cdas2_v1_ssi.fd ; make clean
	cd cdas2_v1_fix_snowc.cd ; make clean
	cd cdas2_v1_snowd2snowc.cd ; make clean
	cd cdas2_v1_fix_afwa_snow.cd  ; make clean
	cd cdas2_v1_fix_snowc.cd ; make clean
	touch ../exec/junk ; rm ../exec/*
