SHELL=/bin/sh

LIBS=-L/nwprod/lib -lw3nco_d
BUFR=-L/nwprod/lib -lbufr_d_64

FFLAGS=-O2 -r8 -convert big_endian -assume byterecl -assume protect_parens
#FFLAGS2=-O2 -r8 -assume byterecl

PROG=r2_oiqc
TARGET = cdas2_v1_oiqc
OBJS = r2_oiqc.o ufbrew.o

${TARGET}:   ${OBJS} 
	ifort $(FFLAGS) -o ${TARGET} $(OBJS) $(LIBS) $(BUFR)

${PROG}.o: ${PROG}.f
	ifort $(FFLAGS) -c  ${PROG}.f

ufbrew.o: ufbrew.f
	ifort $(FFLAGS2) -c  ufbrew.f

clean:
	rm *.o ${TARGET}
