      PROGRAM COMBBUFR
      CHARACTER*8 SUBSET
      DATA LUNIN,LUNOT/20,50/
      READ(5,*) NUM
      DO LUNIN=20,20+NUM-1
      IF(LUNIN.EQ.20) THEN
         CALL OPENBF(LUNIN,'IN ',LUNIN)
         CALL OPENBF(LUNOT,'OUT',LUNIN)
      ELSE
         CALL OPENBF(LUNIN,'IN ',LUNOT)
      ENDIF
      DO WHILE(IREADMG(LUNIN,SUBSET,IDATE).EQ.0)
         CALL COPYMG(LUNIN,LUNOT)
      ENDDO
      ENDDO
      STOP
      END
